"""Initial migration: Create todos table with all fields and indexes

Revision ID: 1f3b51782d61
Revises: 
Create Date: 2025-06-11 01:25:13.361409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3b51782d61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priorityenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='statusenum'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(title)) > 0', name='check_title_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index('idx_todos_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_todos_due_date', ['due_date'], unique=False)
        batch_op.create_index('idx_todos_status', ['status'], unique=False)
        batch_op.create_index('idx_todos_status_due_date', ['status', 'due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index('idx_todos_status_due_date')
        batch_op.drop_index('idx_todos_status')
        batch_op.drop_index('idx_todos_due_date')
        batch_op.drop_index('idx_todos_created_at')

    op.drop_table('todos')
    # ### end Alembic commands ###
